#!/bin/bash

if `test $TRAVIS_BRANCH='stable'`; then
    sudo apt-add-repository ppa:tsuru/ppa -y
    sudo apt-get update -qq
    sudo apt-get install gandalf-server -qq
else
    sudo apt-get install golang -qq
    mkdir -p /tmp/go/{bin,pkg,src}
    cd /tmp/go/src
    rm -rf /tmp/go/src/gandalf
    export GOPATH=/tmp/go
    git clone https://github.com/tsuru/gandalf.git
    cd gandalf
    make get
    go build webserver/main.go
    mv main /home/travis/.rvm/bin/gandalf-server
    cd $TRAVIS_BUILD_DIR
fi

git config --global user.email "foo@bar.com"
git config --global user.name "Foo Bar"